#!/bin/sh
bsteam_version='1.0.0'

bsteam_config="$HOME/.config/bsteam/"
steamcred_file="$bsteam_config/credentials.txt"

if [ -e "$steamcred_file" ]; then
    . $steamcred_file
fi

steamcmd_url="https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
steamcmd_dir="$bsteam_config/steamcmd"
steamcmd="$steamcmd_dir/steamcmd.sh"

if [ ! -e "$steamcmd" ]; then
    echo "Downloading steamcmd..."
    mkdir -p "$steamcmd_dir"
    curl -sqL "$steamcmd_url" | tar -zxf - -C "$steamcmd_dir"
fi

parse_app() {
    unset retval
    case $1 in
        starbound) retval=211820;;
        terraria)  retval=105600;;
        *)         retval=$1;;
    esac
}

update() {
    parse_app $1
    app=$retval
    unset retval
    $steamcmd +login $steam_user $steam_passwd +app_update $app +quit
}

install() {
    update $@
}

uninstall() {
    parse_app $1
    app=$retval
    unset retval
    $steamcmd +login $steam_user $steam_passwd +app_uninstall $app
}

read_credentials() {
    echo "Steam username? "
    read steam_user
    echo "Steam passwd? "
    read steam_passwd
    touch $steamcred_file
    cat << EOF > $steamcred_file
steam_user=$steam_user
steam_passwd=$steam_passwd
EOF
}

run() {
    parse_app $1
    app=$retval
    unset retval
    dir=$(dirname $(realpath "$0"))
    exe="$dir/run_$app"
    if [ -f "$exe" ]; then
        $exe
    else
        print_error "No $exe found"
    fi
}

print_help() {
    echo "bsteam can perform one of the following commands"
    echo ""
    echo "update.........................install/update an <appid>"
    echo "install........................install/update an <appid>"
    echo "uninstall...........................uninstall an <appid>"
    echo "ping.................................test login and quit"
    echo "print_help................................show this text"
    echo "update_script.........................update this script"
    echo "print_version..........................print the version"
    echo "run.......................................run an <appid>"
    echo ""
    echo "An <appid> can be a single numerical steam appid or a hardcoded
    translation"
}

ping() {
    $steamcmd +login $steam_user $steam_passwd +quit
}

print_error() {
    echo $1
    exit 1
}

update_script() {
    update_url='https://raw.githubusercontent.com/dargonforce/bsteam/master/bsteam'
    target_file=$(realpath "$0")
    curl $update_url -o $target_file
}

print_version() {
    echo "$bsteam_version"
}

invoke() {
    cmd=$1
    case $cmd in
        update|install|uninstall|ping|print_help|update_script|print_version|run)
	    $@
	    ;;
	*)
	    print_error 'Invalid command'
	    ;;
    esac
}

if [ -z "$steam_user" ] || [ -z "$steam_passwd" ]; then
    read_credentials
fi

if [ "$#" -eq "0" ]; then
    invoke print_help
else
    invoke $@
fi
